# Settings related to the sidebar
sidebar:

  # Define which posts are featured on the sidebar from different groups
  featured:
    topics:
    - pack
    - fonts
    - blocks
    - items
    - sounds
    - shaders
    - entities
    guides:
    - adding-spaces
    - creating-blocks
    - custom-armor
    - textures-guis

# Group settings
# All posts are split into groups. 
groups:
 
  home:
    title: 'Home'
    slug: 'home'
     
  # Group that will just contain posts
  topics:
    title: 'Topics'
    slug: 'topics' # Optional
    
  # Group that will contain posts sortable by given tags
  guides:
    title: 'Guides'
    tags:
      fonts:
        title: 'Fonts'
        background: '#FFD700'
        text-color: '#000000' 
      blocks:
        title: 'Blocks'
        background: '#008000'
        text-color: '#FFFFFF' 
      entities:
        title: 'Entities'
        background: '#4169E1'
        text-color: '#FFFFFF' 
      items:
        title: 'Items'
        background: '#4287f5'
        text-color: '#edeef0'

